### PR TITLE
Added the ability to use msbuild project properties for command arguments

### PR DESCRIPTION
**Pull request by Sergey-Vlasov**
Properties like $(MSBuildStartupDirectory), $(WholeProgramOptimization) etc.

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks

**Comment by solvingj** [comment]
Looking forward to testing this out.  Is there a new minor version release coming soon?

**Comment by madskristensen** [comment]
@solvingj You can test the latest build here http://vsixgallery.com/extension/fc1aafb2-321e-41bd-ac37-03b09ea8ef31/

**Comment by solvingj** [comment]
yes, just curious about when my colleagues will be able to get these and some other recent changes directly from the marketplace.

**Pull request merged**
